# Generated by Django 2.2 on 2020-08-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.CharField(default='old posts', max_length=255),
            preserve_default=False,
        ),
    ]
